### ISSUE TITLE
Incorrect Hierarchy

### ISSUE THREAD

**Issue by jrakshit749** [pccoeacm/pccoeacm.github.io#20]
### The hierarchy looks like an iPhone Camera module, it should be 
- President
- Vice Presidents

page URL - https://pccoe.acm.org/aboutpccoeacm.html

![image](https://user-images.githubusercontent.com/66620914/103440432-6682ec80-4c6b-11eb-8094-f187578dad53.png)

**Comment by palakg01** [comment]
on it

**Comment by JayeshShelar** [comment]
Required changes are done!
