### ISSUE TITLE
Addition of event names

### ISSUE THREAD

**Issue by jrakshit749** [pccoeacm/pccoeacm.github.io#21]
### Activities

- Blog writing 
- Film making competition
- Quarantine Quiz
- Google facilitator
- E-yantra awareness session
- Animal Welfare activity
- Digital art competition
- Digital Poster making
- Sardar Vallabhai Patel oath
- Hour of code 2020
- HackerRank weekly coding Contest 2020 

> For images contact the Social Media & Design team

#### Images to be uploaded on:
Page URL - https://pccoe.acm.org/acm_activities.html

**Comment by tejasmorkar** [comment]
@JayeshShelar should this issue be closed?
